### ISSUE TITLE
Regarding Installation of packages

### ISSUE THREAD

**Issue by karanpratap** [git-akshat/NP-Lab#4]
apt-get is deprecated. Shouldn't one use apt to install the required packages? Also, it only works for distros that use apt as their package manager. What about systems like Fedora, or systems that do not have a package manager?

**Comment by git-akshat** [comment]
The instructions are provided for most common and popularly used operating systems( like ubuntu, mint, kali, elementary etc). For other operating systems, when you type this command it will show an error message along with  the solution. You just have to follow up the instructions shown on the screen. If you can send me a pull request with the correct command or with proper set of instructions I'll update it. Thanks.

**Comment by git-akshat** [comment]
Request received from karan to reopen the issue. Waiting for updated commands from karan.

**Comment by nateshmbhat** [comment]
@karanpratap  its totally fine to only support a few package managers you know .... If people are good enough to use non default and non standard ones , then they should also be good enough to figure out the command from looking at the standard commands.

**Comment by nateshmbhat** [comment]
its better we close this issue @git-akshat

**Comment by karanpratap** [comment]
I apologize for delaying. I shall send a pull request within next 24 hours.

**Comment by git-akshat** [comment]
Pull request received from @karanpratap . Closing the issue now.
